# Generated by Django 3.2.7 on 2022-06-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0006_alter_registrationform_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='unknown', max_length=200)),
                ('message', models.TextField(blank=True, default='no feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_Description',
            fields=[
                ('Disease', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_Precaution',
            fields=[
                ('Disease', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Precaution_1', models.CharField(max_length=255)),
                ('Precaution_2', models.CharField(max_length=255)),
                ('Precaution_3', models.CharField(max_length=255)),
                ('Precaution_4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('request', models.TextField(blank=True)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.updateform')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
