# Generated by Django 3.2.7 on 2022-06-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom_Description',
        ),
        migrations.DeleteModel(
            name='Symptom_Precaution',
        ),
    ]
