# Generated by Django 3.2.7 on 2022-06-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_registrationform_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateform',
            name='image',
            field=models.ImageField(upload_to='media/media/image'),
        ),
    ]
