# Generated by Django 3.2.7 on 2022-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_updateform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateform',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
